messages:
  prefix: "&3[lGenerators]&f"
  pluginEnabled: "%prefix% Plugin has been &aEnabled&f!"
  pluginDisabled: "%prefix% Plugin has been &cDisabled&f!"
  help:
    - ""
    - "&fHelp page"
    - ""
    - ""
    - ""
  generatorPlaced: "%prefix% You have placed the &e%type% &fgenerator!"
  generatorBroken: "%prefix% You have broken the generator!"
  generatorUpgraded: "%prefix% You have upgraded your generator to level &e%level%&f!"
  alreadyOpened: "&c&l[!]&c Somebody is just interacting with the generator!"
  notEnoughMoney: "&c&l[!]&c You don't have enough money to do that!"
  commands:
    give:
      given: "%prefix% You got the &e%type% &fgenerator!"
      notEnoughArgs: "&c&l[!]&c Not enough arguments! Use /lgenerators give <Type> [Player]"
      unknownType: "&c&l[!]&c There's no generator with this identifier!"

settings:
  commandAliases:
    - generators
    - gens
    - lgens
    - gen
    - lgen
  permissions:
    give: "lgenerators.admin.give"
  database:
    # TYPES: SQLITE, MYSQL
    type: SQLITE
    # ONLY FOR MYSQL
    login:
      host: "localhost"
      port: 3306
      user: "root"
      password: ""
      database: "lGenerators"
      table: "lGenerators"

generators:
  wheat:
    block: HAY_BLOCK
    drop:
      material: WHEAT
    display:
      material: PLAYER_HEAD
      displayName: "&6Wheat &fGenerator"
      lore:
        - ""
        - "&7- &fLevel&7: &e%level%"
        - "&7- &fSpeed&7: &e%speed%"
        - "&7- &fAmount&7: &e%amount%"
        - ""
        - "&7&oPlace to activate!"
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWFmMzI4Yzg3YjA2ODUwOWFjYTk4MzRlZmFjZTE5NzcwNWZlNWQ0ZjA4NzE3MzFiN2IyMWNkOTliOWZkZGMifX19"
    hologram:
      enabled: true
      offset:
        x: 0.5
        y: 1
        z: 0.5
      lines:
        - "&6Wheat Generator"
        - ""
        - "&fLevel&7: &e%level%"
        - "&fSpeed&7: &e%speed%"
        - "&fAmount&7: &e%amount%"
    inventory:
      shape:
        - "#########"
        - "   u i   "
        - "########r"
      title: "Wheat Generator"
      functions:
        upgrade: 'u'
        remove: 'r'
      items:
        '#':
          material: BLACK_STAINED_GLASS_PANE
          displayName: "&f "
        'u':
          material: EMERALD
          displayName: "&2Upgrade"
          lore:
            - ""
            - "&aUpgrade to level &2%next-level%&a:"
            - "&7- &fSpeed&7: &a%next-speed%"
            - "&7- &fAmount&7: &a%next-amount%"
            - "&7- &fPrice&7: &c$%price%"
            - ""
            - "&7&oClick to upgrade!"
          maxLvlLore:
            - ""
            - "&c! MAX LEVEL !"
        'r':
          material: BARRIER
          displayName: "&4Remove"
          lore:
            - ""
            - "&7&oClick to remove!"
        'i':
          material: BOOK
          displayName: "&6Info"
          lore:
            - ""
            - "&fType&7: &e%type%"
            - ""
            - "&eLevel &6%level%&e:"
            - "&7- &fSpeed&7: &e%speed%"
            - "&7- &fAmount&7: &e%amount%"
    upgrades:
      1: #DEFAULT
        price: 1000
        timer: 30
        amount: "1-2"
      2:
        price: 2000
        timer: 20
        amount: "1-3"
      3:
        price: 3000
        timer: 10
        amount: "2-4"